version: "3.8"

services:
  traefik:
    build: .
    container_name: traefik
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /data/letsencrypt:/letsencrypt
      - ./logs:/logs
      # Mount the dynamic configuration file
      - ./dynamic_conf.yml:/traefik/dynamic_conf.yml:ro
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik_https.rule=Host(`traefik.abdo.agency`)
      - traefik.http.routers.traefik_https.entrypoints=https
      - traefik.http.routers.traefik_https.tls=true
      - traefik.http.routers.traefik_https.tls.certresolver=simple-resolver
      - traefik.http.routers.traefik_https.service=api@internal
networks:
  traefik:
    name: traefik
    external: true

