version: "3.8"

services:
  db:
    build: .
    container_name: drupal-db
    restart: always
    networks:
      - backend
    environment:
      - POSTGRES_USER=drupal
      - POSTGRES_PASSWORD=drupal
      - POSTGRES_DB=drupal
    ports:
      - '5432:5432'
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
      - postgres_data:/var/lib/postgresql/data

networks:
  backend:
    external: true

volumes:
  postgres_data:
